---
title: フォールバック
excerpt: "`orElse`を使用して代替エフェクトを試みる、`orElseFail`および`orElseSucceed`で失敗を修正する、`firstSuccessOf`で最初に成功したエフェクトの結果を取得するなど、Effectにおける失敗とフォールバックの処理技術を探ります。エラーを優雅に処理し、Effectプログラムでフォールバックメカニズムを作成する方法を学びます。"
bottomNavigation: pagination
---

## orElse

一つのエフェクトを試みて、それが失敗した場合、`Effect.orElse`コンビネータを使用して別のエフェクトを試みることができます：

```ts twoslash
import { Effect } from "effect"

const success = Effect.succeed("success")
const failure = Effect.fail("failure")
const fallback = Effect.succeed("fallback")

const program1 = Effect.orElse(success, () => fallback)
console.log(Effect.runSync(program1)) // 出力: "success"

const program2 = Effect.orElse(failure, () => fallback)
console.log(Effect.runSync(program2)) // 出力: "fallback"
```

## orElseFail / orElseSucceed

これらの2つのオペレータは、元の失敗を定数の成功または失敗の値に置き換えます。

`Effect.orElseFail`は常に元の失敗を新しい失敗に置き換えます：

```twoslash include validate
import { Effect } from "effect"

class NegativeAgeError {
  readonly _tag = "NegativeAgeError"
  constructor(readonly age: number) {}
}

class IllegalAgeError {
  readonly _tag = "IllegalAgeError"
  constructor(readonly age: number) {}
}

const validate = (
  age: number
): Effect.Effect<number, NegativeAgeError | IllegalAgeError> => {
  if (age < 0) {
    return Effect.fail(new NegativeAgeError(age))
  } else if (age < 18) {
    return Effect.fail(new IllegalAgeError(age))
  } else {
    return Effect.succeed(age)
  }
}
```

```ts twoslash
// @include: validate

const program1 = Effect.orElseFail(validate(3), () => "invalid age")
```

`Effect.orElseSucceed`関数は、常に元の失敗を成功値に置き換えるため、結果として得られるエフェクトは失敗することができません：

```ts twoslash
// @include: validate
// ---cut---
const program2 = Effect.orElseSucceed(validate(3), () => 0)
```

## firstSuccessOf

`firstSuccessOf`オペレータは、一連のエフェクトを実行し、最初に成功したエフェクトの結果を返すことを簡素化します。どのエフェクトも成功しなかった場合、結果として得られるエフェクトは、シリーズ内の最後のエフェクトのエラーで失敗します。

このオペレータは、複数のエフェクトを単一のエフェクトに結合するために`Effect.orElse`を利用します。

次の例では、異なるノードから設定を取得しようとします。プライマリノードからの取得が失敗した場合、次に利用可能なノードから順次取得を試み、成功する結果が見つかるまで続けます：

```ts twoslash
import { Effect, Console } from "effect"

interface Config {
  // ...
}

const makeConfig = (/* ... */): Config => ({})

const remoteConfig = (name: string): Effect.Effect<Config, Error> =>
  Effect.gen(function* () {
    if (name === "node3") {
      yield* Console.log(`Config for ${name} found`)
      return makeConfig()
    } else {
      yield* Console.log(`Unavailable config for ${name}`)
      return yield* Effect.fail(new Error())
    }
  })

const masterConfig = remoteConfig("master")

const nodeConfigs = ["node1", "node2", "node3", "node4"].map(remoteConfig)

const config = Effect.firstSuccessOf([masterConfig, ...nodeConfigs])

console.log(Effect.runSync(config))
/*
Output:
Unavailable config for master
Unavailable config for node1
Unavailable config for node2
Config for node3 found
{}
*/
```

<Warning>
  `Effect.firstSuccessOf`関数に提供されたコレクションが空の場合、`IllegalArgumentException`エラーがスローされます。
</Warning>
