---
title: タイムアウト
excerpt: `Effect.timeout`を使用して操作に時間制限を設定する方法を学びます。タスクが指定された時間内に完了する必要があるシナリオの処理方法を発見します。タイムアウトが発生したときの動作をカスタマイズするための`timeoutTo`、`timeoutFail`、および`timeoutFailCause`のようなバリエーションを探求し、時間に敏感な操作を管理する際の制御と柔軟性を向上させます。
bottomNavigation: pagination
---

プログラミングの世界では、完了するのに時間がかかるタスクを扱うことがよくあります。時には、タスクが完了するまでに待つ時間に制限を設けたいことがあります。ここで`Effect.timeout`関数が役立ちます。これにより、操作に時間制限を設定し、無期限に実行されないようにすることができます。このガイドでは、`Effect.timeout`を効果的に使用する方法を探ります。

## timeout

Effectは`Effect.timeout`関数を使用して任意のエフェクトにタイムアウトを設定することができます。これにより、次の特性を持つ新しいエフェクトが返されます：

- エラーが返された場合、それはエフェクトの実行が完了する前にタイムアウトが発生したことを示します。
- 成功した場合、それはエフェクトが指定されたタイムアウト内に完了し、その結果が含まれていることを示します。

エフェクトがタイムアウトした場合、バックグラウンドで実行を続けるのではなく、中断されるため、リソースが無駄になりません。

次のようなエフェクトがあるとします：

```ts twoslash
import { Effect } from "effect"

const program = Effect.gen(function* () {
  console.log("start doing something...")
  yield* Effect.sleep("2 seconds")
  console.log("my job is finished!")
  return "some result"
})

const main = program.pipe(Effect.timeout("3 seconds"))
```

`Effect.timeout`を`program`に適用すると、次のいずれかの方法で動作します：

1. 元のエフェクト（この場合は`program`）がタイムアウトが経過する前に完了した場合、元のエフェクトによって生成された値を返します。以下はその例です：

   ```ts twoslash
   import { Effect } from "effect"

   const program = Effect.gen(function* () {
     console.log("start doing something...")
     yield* Effect.sleep("2 seconds")
     console.log("my job is finished!")
     return "some result"
   })

   const main = program.pipe(Effect.timeout("3 seconds"))

   Effect.runPromise(main).then(console.log, console.error)
   /*
   出力:
   start doing something...
   my job is finished!
   some result
   */
   ```

2. タイムアウトが元のエフェクトの完了前に経過し、エフェクトが中断可能である場合、即座に中断され、タイムアウト操作は`TimeoutException`エラーを生成します。以下はその例です：

   ```ts twoslash
   import { Effect } from "effect"

   const program = Effect.gen(function* () {
     console.log("start doing something...")
     yield* Effect.sleep("2 seconds")
     console.log("my job is finished!")
     return "some result"
   })

   const main = program.pipe(Effect.timeout("1 second"))

   Effect.runPromise(main).then(console.log, console.error)
   /*
   出力:
   (FiberFailure) TimeoutException
      ... stack trace ...
   */
   ```

3. エフェクトが中断不可能な場合、元のエフェクトが安全に作業を完了するまでブロックされ、その後タイムアウト操作は`TimeoutException`エラーを生成します。以下はその例です：

   ```ts twoslash
   import { Effect } from "effect"

   const program = Effect.gen(function* () {
     console.log("start doing something...")
     yield* Effect.sleep("2 seconds")
     console.log("my job is finished!")
     return "some result"
   })

   const main = program.pipe(
     Effect.uninterruptible,
     Effect.timeout("1 second")
   )

   Effect.runPromise(main).then(console.log, console.error)
   /*
   出力:
   start doing something...
   my job is finished!
   (FiberFailure) TimeoutException
      ... stack trace ...
   */
   ```

   タイムアウトが経過した後、基礎となるエフェクトが中断される前に早期に戻りたい場合は、`Effect.disconnect`を使用できます。この技法により、元のエフェクトはバックグラウンドで中断されることが可能です。以下はその例です：

   ```ts twoslash
   import { Effect } from "effect"

   const program = Effect.gen(function* () {
     console.log("start doing something...")
     yield* Effect.sleep("2 seconds")
     console.log("my job is finished!")
     return "some result"
   })

   const main = program.pipe(
     Effect.uninterruptible,
     Effect.disconnect,
     Effect.timeout("1 second")
   )

   Effect.runPromise(main).then(console.log, console.error)
   /*
   出力:
   start doing something...
   (FiberFailure) TimeoutException
      ... stack trace ...
   my job is finished!
   */
   ```

## タイムアウト動作のカスタマイズ

基本的な`Effect.timeout`関数に加えて、タイムアウトが発生したときの動作をカスタマイズできるバリエーションがあります。

### timeoutTo

`timeoutTo`関数は`Effect.timeout`に似ていますが、最終的な結果の型をより細かく制御できます。タイムアウトが発生した場合に返すべき内容を指定することができます。以下はその例です：

```ts twoslash
import { Effect, Either } from "effect"

const program = Effect.gen(function* () {
  console.log("start doing something...")
  yield* Effect.sleep("2 seconds")
  console.log("my job is finished!")
  return "some result"
})

const main = program.pipe(
  Effect.timeoutTo({
    duration: "1 second",
    // Eitherを返しましょう
    onSuccess: (result): Either.Either<string, string> =>
      Either.right(result),
    onTimeout: (): Either.Either<string, string> => Either.left("timeout!")
  })
)

Effect.runPromise(main).then(console.log)
/*
出力:
start doing something...
{
  _id: "Either",
  _tag: "Left",
  left: "timeout!"
}
*/
```

### timeoutFail

`timeoutFail`関数は、タイムアウトが発生したときに特定のエラーを生成することができます。これは、コード内でタイムアウトエラーを通知するのに役立ちます。以下はその例です：

```ts twoslash
import { Effect } from "effect"

const program = Effect.gen(function* () {
  console.log("start doing something...")
  yield* Effect.sleep("2 seconds")
  console.log("my job is finished!")
  return "some result"
})

const main = program.pipe(
  Effect.timeoutFail({
    duration: "1 second",
    onTimeout: () => new Error("timeout")
  })
)

Effect.runPromise(main).then(console.log, console.error)
/*
出力:
start doing something...
(FiberFailure) Error: timeout
*/
```

### timeoutFailCause

`timeoutFailCause`関数は、タイムアウトが発生したときに特定の欠陥を生成することができます。これは、コード内でタイムアウトを例外的なケースとして処理するのに役立ちます。以下はその例です：

```ts twoslash
import { Effect, Cause } from "effect"

const program = Effect.gen(function* () {
  console.log("start doing something...")
  yield* Effect.sleep("2 seconds")
  console.log("my job is finished!")
  return "some result"
})

const main = program.pipe(
  Effect.timeoutFailCause({
    duration: "1 second",
    onTimeout: () => Cause.die("timeout")
  })
)

Effect.runPromiseExit(main).then(console.log)
/*
出力:
start doing something...
{
  _id: 'Exit',
  _tag: 'Failure',
  cause: { _id: 'Cause', _tag: 'Die', defect: 'timeout' }
}
*/
```
