---
title: サンドボックス化
excerpt: 強力な `Effect.sandbox` 関数を利用して、コード内のエラーの原因をカプセル化し理解する方法を学びます。このガイドではエラーのサンドボックス化を探求し、エラーの詳細な原因を明らかにし、`Effect.catchAll` や `Effect.catchTags` などの標準的なエラーハンドリングオペレーターを使用して特定のエラー条件を効果的に処理する方法を示します。
bottomNavigation: pagination
---

エラーはプログラミングの一般的な一部であり、失敗、欠陥、ファイバーの中断、またはこれらの要因の組み合わせなど、さまざまな理由で発生する可能性があります。このガイドでは、`Effect.sandbox` 関数を使用してコード内のエラーの原因を分離し理解する方法を探ります。

## サンドボックス

`Effect.sandbox` 関数は、エラーのすべての潜在的な原因をエフェクト内にカプセル化するための貴重なツールです。失敗、欠陥、ファイバーの中断、またはこれらの要因の組み合わせによるものであっても、エフェクトの完全な原因を明らかにします。

こちらが `Effect.sandbox` 関数のシグネチャです：

```ts
sandbox: Effect<A, E, R> -> Effect<A, Cause<E>, R>
```

簡単に言うと、`Effect<A, E, R>` というエフェクトを `Effect<A, Cause<E>, R>` というエフェクトに変換し、エラーチャンネルにエラーの詳細な原因を含めることができます。

`Effect.sandbox` 関数を使用することで、例外的なエフェクトの根本的な原因にアクセスできます。これらの原因は `Cause<E>` 型として表され、`Effect` データ型のエラーチャンネルで利用可能です。

原因を明らかにしたら、`Effect.catchAll` や `Effect.catchTags` などの標準的なエラーハンドリングオペレーターを利用して、エラーをより効果的に処理できます。これらのオペレーターを使用すると、特定のエラー条件に対応することができます。

エラーのサンドボックス化がどのように機能するかを示す例を見てみましょう：

```ts twoslash
import { Effect, Console } from "effect"

const effect = Effect.fail("Oh uh!").pipe(Effect.as("primary result"))

const sandboxed = Effect.sandbox(effect)

const program = Effect.catchTags(sandboxed, {
  Die: (cause) =>
    Console.log(`Caught a defect: ${cause.defect}`).pipe(
      Effect.as("fallback result on defect")
    ),
  Interrupt: (cause) =>
    Console.log(`Caught a defect: ${cause.fiberId}`).pipe(
      Effect.as("fallback result on fiber interruption")
    ),
  Fail: (cause) =>
    Console.log(`Caught a defect: ${cause.error}`).pipe(
      Effect.as("fallback result on failure")
    )
})

const main = Effect.unsandbox(program)

Effect.runPromise(main).then(console.log)
/*
出力:
Caught a defect: Oh uh!
fallback result on failure
*/
```

この例では、`Effect.sandbox` を使用してエフェクトの完全な原因を明らかにします。次に、`Effect.catchTags` を使用して特定のエラー条件を処理します。最後に、必要に応じて `Effect.unsandbox` を使ってサンドボックス化の操作を元に戻すことができます。
