---
title: Effectでジェネレーターを使用する
excerpt: Effectでジェネレーターを使用して効果的なコードを書くための構文を探ります。`Effect.gen`関数について学びます。非同期コードを書くための`Effect.gen`と`async`/`await`の比較を行います。ジェネレーターがどのように制御フローを強化し、エラーを処理し、効果的なプログラムでショートサーキットを利用するかを理解します。ジェネレーター関数で`this`への参照を渡す方法を発見します。
bottomNavigation: pagination
---

前のセクションでは、[Effectを作成](./creating-effects)し、それらを[実行](./running-effects)する方法を学びました。今度は、最初のシンプルなプログラムを書いてみましょう。

Effectは、[ジェネレーター](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator)を使用して効果的なコードを書くための、`async`/`await`に似た便利な構文を提供します。

<Idea>
  ジェネレーターの使用はEffectにおいて**オプションの機能**です。
  ジェネレーターに馴染みがない場合や、異なるコーディングスタイルを好む場合は、
  Effectの[パイプラインの構築](./pipeline)に関するドキュメントを参照してください。
</Idea>

## Effect.genの理解

一連の変換を行う基本的なプログラムから始めましょう：

```ts twoslash
import { Effect } from "effect"

const increment = (x: number) => x + 1

const divide = (a: number, b: number): Effect.Effect<number, Error> =>
  b === 0
    ? Effect.fail(new Error("Cannot divide by zero"))
    : Effect.succeed(a / b)

const task1 = Effect.promise(() => Promise.resolve(10))

const task2 = Effect.promise(() => Promise.resolve(2))

export const program = Effect.gen(function* () {
  const a = yield* task1
  const b = yield* task2
  const n1 = yield* divide(a, b)
  const n2 = increment(n1)
  return `Result is: ${n2}`
})

Effect.runPromise(program).then(console.log) // 出力: "Result is: 6"
```

<Warning>
  ジェネレーターAPIは、`downlevelIteration`フラグを使用するか、
  `tsconfig.json`ファイルの`target`を`"es2015"`以上に設定した場合にのみ利用可能です。
</Warning>

## Effect.genとasync/awaitの比較

`async`/`await`に慣れている場合、コードを書く流れが似ていることに気付くかもしれません。

この2つのアプローチを比較してみましょう：

<Tabs items={['Effect.genの使用', 'async / awaitの使用']}>
  <Tab>

```ts twoslash
import { Effect } from "effect"
// ---cut---
const increment = (x: number) => x + 1

const divide = (a: number, b: number): Effect.Effect<number, Error> =>
  b === 0
    ? Effect.fail(new Error("Cannot divide by zero"))
    : Effect.succeed(a / b)

const task1 = Effect.promise(() => Promise.resolve(10))

const task2 = Effect.promise(() => Promise.resolve(2))

export const program = Effect.gen(function* () {
  const a = yield* task1
  const b = yield* task2
  const n1 = yield* divide(a, b)
  const n2 = increment(n1)
  return `Result is: ${n2}`
})

Effect.runPromise(program).then(console.log) // 出力: "Result is: 6"
```

  </Tab>
  <Tab>

```ts twoslash
const increment = (x: number) => x + 1

const divide = (a: number, b: number): Promise<number> =>
  b === 0
    ? Promise.reject(new Error("Cannot divide by zero"))
    : Promise.resolve(a / b)

const task1 = Promise.resolve(10)

const task2 = Promise.resolve(2)

export const program = async function () {
  const a = await task1
  const b = await task2
  const n1 = await divide(a, b)
  const n2 = increment(n1)
  return `Result is: ${n2}`
}

program().then(console.log) // 出力: "Result is: 6"
```

  </Tab>
</Tabs>

コードが似ているように見えても、2つのプログラムは同一ではないことに注意してください。並べて比較する目的は、書き方の類似性を強調するためだけです。

## 制御フローの活用

ジェネレーターと組み合わせて `Effect.gen` を使用する大きな利点の一つは、ジェネレーター関数内で標準的な制御フロー構造を使用できることです。これらの構造には、`if`/`else`、`for`、`while` などの分岐やループのメカニズムが含まれており、コード内で複雑な制御フローのロジックを表現する能力が向上します。

これを実証するために、実際の例を見てみましょう：

```ts twoslash
import { Effect } from "effect"

const divide = (a: number, b: number): Effect.Effect<number, Error> =>
  b === 0
    ? Effect.fail(new Error("Cannot divide by zero"))
    : Effect.succeed(a / b)

const program = Effect.gen(function* () {
  let i = 1

  while (true) {
    if (i === 10) {
      break
    } else {
      if (i % 2 === 0) {
        console.log(yield* divide(12, i))
      }
      i++
      continue
    }
  }
})

Effect.runPromise(program)
/*
出力:
6
3
2
1.5
*/
```

## エラーの発生

`Effect.gen` APIの領域内では、失敗したEffectをyieldすることでプログラムにエラーを導入することができます。例えば、`Effect.fail`を使用することでこれを効果的に達成できます。具体例を見てみましょう：

```ts twoslash
import { Effect } from "effect"

const program = Effect.gen(function* () {
  console.log("Task1...")
  console.log("Task2...")
  yield* Effect.fail("Something went wrong!")
})

Effect.runPromiseExit(program).then(console.log)
/*
出力:
Task1...
Task2...
{
  _id: 'Exit',
  _tag: 'Failure',
  cause: { _id: 'Cause', _tag: 'Fail', failure: 'Something went wrong!' }
}
*/
```

この例では、`Effect.fail`を使用して意図的にエラーを導入し、プログラム内でエラーをどのように管理できるかを示しています。

### ショートサーキットの役割

`Effect.gen` APIを使用する際には、エラーの管理方法を理解することが重要です。
このAPIは、**最初のエラー**に遭遇した時点で**実行をショートサーキット**するように設計されています。

開発者としてこれが何を意味するかというと、例えば一連の操作や一連のEffectを順番に実行する場合、これらのEffectの実行中にエラーが発生すると、残りの計算はスキップされ、そのエラーが最終結果に伝播されるということです。

簡単に言えば、ショートサーキットの動作は、プログラムのどのステップで問題が発生しても、即座に停止してエラーを返し、何が問題だったのかを知らせてくれることを保証します。

```ts twoslash
import { Effect } from "effect"

const program = Effect.gen(function* () {
  console.log("Task1...")
  console.log("Task2...")
  yield* Effect.fail("Something went wrong!")
  console.log("This won't be executed")
})

Effect.runPromise(program).then(console.log, console.error)
/*
出力:
Task1...
Task2...
{
  _id: 'Exit',
  _tag: 'Failure',
  cause: { _id: 'Cause', _tag: 'Fail', failure: 'Something went wrong!' }
}
*/
```

<Info>
  Effectを使った効果的なエラーハンドリングについてさらに詳しく知りたい場合は、
  ["エラーマネジメント"](../error-management/two-error-types)セクションを参照してください。
</Info>

## thisの渡し方

場合によっては、ジェネレータ関数の本体に現在のオブジェクト（`this`）への参照を渡す必要があるかもしれません。この場合、最初の引数として参照を受け取るオーバーロードを利用することで実現できます：

```ts twoslash
import { Effect } from "effect"

class MyService {
  readonly local = 1
  compute = Effect.gen(this, function* () {
    return yield* Effect.succeed(this.local + 1)
  })
}

console.log(Effect.runSync(new MyService().compute)) // 出力: 2
```

この例では、`local`というプロパティを持つ`MyService`クラスがあります。`Effect.gen`に最初の引数として`this`を渡すことで、ジェネレータ内で`local`プロパティを利用可能にしています。
