---
title: Exit
excerpt: `Effect`ワークフローを実行した結果を表す`Exit`データ型を探求します。成功と失敗の状態、`Exit.match`によるマッチング、`Exit`と`Either`の概念的な関係について学びます。`Exit`が`Effect`のサブタイプであり、結果とエラーの処理における役割を理解します。
bottomNavigation: pagination
---

`Exit<A, E>`は、`Effect`ワークフローを実行した結果を表します。

`Exit<A, E>`には2つの可能な値があります：

- `Exit.Success`は、型`A`の成功値を含みます。
- `Exit.Failure`は、型`E`の失敗[Cause](cause)を含みます。

## Matching

`Exit`の異なる結果を処理するために、`Exit.match`関数を使用できます。

```ts twoslash
import { Effect, Exit } from "effect"

const simulatedSuccess = Effect.runSyncExit(Effect.succeed(1))

Exit.match(simulatedSuccess, {
  onFailure: (cause) =>
    console.error(`Exited with failure state: ${cause._tag}`),
  onSuccess: (value) => console.log(`Exited with success value: ${value}`)
})
// 出力: "Exited with success value: 1"

const simulatedFailure = Effect.runSyncExit(Effect.fail("error"))

Exit.match(simulatedFailure, {
  onFailure: (cause) =>
    console.error(`Exited with failure state: ${cause._tag}`),
  onSuccess: (value) => console.log(`Exited with success value: ${value}`)
})
// 出力: "Exited with failure state: Fail"
```

この例では、まず`Effect.runSyncExit`と`Effect.succeed`を使用して成功した`Effect`の実行をシミュレートします。次に、`Exit.match`を使用して`Exit`を処理し、`onSuccess`コールバックで成功値を出力します。

次に、`Effect.runSyncExit`と`Effect.fail`を使用して失敗をシミュレートし、再度`Exit.match`を使用して`Exit`を処理し、`onFailure`コールバックで失敗状態を出力します。

## Exit vs Either

`Exit<A, E>`は概念的には`Either<A, Cause<E>>`です。しかし、[Cause](cause)は期待されるエラータイプ`E`だけでなく、他の状態（中断や欠陥（予期しないエラー）など）も含むことに注意が必要です。また、複数の`Cause`値を組み合わせる可能性もあります。

## Exit vs Effect

`Exit`データ型は`Effect`型のサブタイプであり、つまり`Exit`自体が`Effect`です。
その理由は、結果が*定数計算*と見なされるためです。
技術的には、`Effect.succeed`は`Exit.succeed`のエイリアスであり、`Effect.fail`は`Exit.fail`のエイリアスです（`Exit`と`Effect`の間の変換を避けることは、ボクシングとアンボクシングにコストがかかるため、パフォーマンスのために重要です）。
